version: "3.3"


services:
       online-store:
           container_name: online-store
           image: yura/online-store
           depends_on:
               - mongo
           restart: always
           build: .
           ports:
             - "5000:5000"
          #  links:
          #    - mongo

          #  volumes: 
          #    - /app
       mongo:
             container_name: mongo
             image: mongo
             restart: always
             volumes:
               - ./data:/data/db
              #  - mongo-data:/var/lib/data/db
             ports:
                - '27017:27017'
volumes: 
  data:
  # mongo-data: